[tool.black]
line-length = 79
skip-string-normalization = true
include = '\.pyi?$'
exclude = '''
(
  .vscode
  |venv
  |migrations/
  |.git
  |__pycache__/
  |__init__.py
  |fixtures/
  |requirements/
  |.gitignore
  |template.env
  |.env
  |.flake8
)
'''